# Generated by Django 3.2.2 on 2021-05-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='ade', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
